### ISSUE TITLE
Watched badge showing when video hasn't been watched

### ISSUE THREAD

**Issue by peachlilac** [sniklaus/youtube-watchmarker#115]
This started fairly recently. I started noticing that select videos I haven't watched are marked as watched by the extension. At first it was a different video that was marked, then I reset and synced my database and the videos marked changed. I only have the mark with the official YT watched badge option checked. I used to have the red bar thingy hidden but I had to turn it on to actually see if I watched it which kinda defeats the purpose of the badge? 
Here are screenshots, see how one vid has the red bar and one doesn't but both are marked as watched. I looked them up on the database using the search function but they don't show up. 

<img src="https://github.com/sniklaus/youtube-watchmarker/assets/155969016/559a90cc-470b-4212-9355-812eede7dede" width="33%" height="33%"> <img src="https://github.com/sniklaus/youtube-watchmarker/assets/155969016/a72a32a9-dbda-4508-a5c0-d2ab6728f686" width="30%" height="30%">

**Comment by sniklaus** [comment]
Thank you for bringing this up, which version of the Watchmarker you are using? And when you refresh the page, are the incorrectly marked videos still marked as such?

**Comment by peachlilac** [comment]
It says version 4.5.1

Yes, refreshed the page, even closed the browser, turned my pc on and off, but the watched mark is still there for those videos. Weirdly enough I saw just now that a live stream waiting room is also marked as watched despite not clicking on it before and it not showing up on my history and database.

<img src="https://github.com/sniklaus/youtube-watchmarker/assets/155969016/b416c601-7b5c-4327-a5fd-be200dbb6d43" height="20%" width="20%">

**Comment by sniklaus** [comment]
And if you search for the video in the Watchmarker's settings it doesn't show up? Have you tried searching for it using the video id (the part after the `watch?v=` in the URL)?

**Comment by peachlilac** [comment]
I tried that and they did show up but under different names. The first two was named the same as two other videos I actually watched. So I tried searching the titles again and they look like duplicates. Strange.
![Screenshot_2](https://github.com/sniklaus/youtube-watchmarker/assets/155969016/599e8d45-2c19-4656-820c-addf0a24355e)
![Screenshot_3](https://github.com/sniklaus/youtube-watchmarker/assets/155969016/05d95a1e-1585-41b2-a04b-e0cd6cd9c06d)

This one is the live stream waiting room. Again, it was titled differently. I tried to delete it and this error showed presumably because YT doesn't show waiting rooms in official history. But the badge is gone now after deleting.
![Screenshot_4](https://github.com/sniklaus/youtube-watchmarker/assets/155969016/83a217f7-c3d1-4973-a488-d45176d11c8a)
<img src="https://github.com/sniklaus/youtube-watchmarker/assets/155969016/1c6448c4-0f38-4824-9b32-16862624c9c5" width="40%" height="40%">

Also, this one is labeled "Videos" on the database but when I clicked on it, it's a video I've watched but with a completely different title. Any idea why this happens?
![Screenshot_5](https://github.com/sniklaus/youtube-watchmarker/assets/155969016/70e31d12-52a4-4d9c-a8d0-235534af9e32)

**Comment by sniklaus** [comment]
I just made some modifications, does the attached version improve things? Make sure to backup your database before you try.

* [chrome.zip](https://github.com/sniklaus/youtube-watchmarker/files/13945734/chrome.zip)
* [firefox (rename the extension to xpi).zip](https://github.com/sniklaus/youtube-watchmarker/files/13945735/firefox.rename.the.extension.to.xpi.zip)

**Comment by L0relei** [comment]
Same issue for me too.

> Also, this one is labeled "Videos" on the database but when I clicked on it, it's a video I've watched but with a completely different title. Any idea why this happens? ![Screenshot_5](https://private-user-images.githubusercontent.com/155969016/295771045-70e31d12-52a4-4d9c-a8d0-235534af9e32.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjI2MTcsIm5iZiI6MTcwNjkyMjMxNywicGF0aCI6Ii8xNTU5NjkwMTYvMjk1NzcxMDQ1LTcwZTMxZDEyLTUyYTQtNGQ5Yy1hOGQwLTIzNTUzNGFmOWUzMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QwMTA1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWI3MTIxNmMzZGU3YTA1YWNiNTBiY2UyYjcwM2IzYzVlMmRjM2ZiMGUwOGFiYzI4NmYyMTU5YThmZTY0ODM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-WNwjQewaU1RtQCUQKbspr3F7zBFETzu6iZy9EyjirU)

I have lines like this in my history, but with videos I didn't watched. I was able to reproduce it: whenever I visit a channel page, if there is a video above the section "Our Members", this video is added to the history of the extension with the name Videos. The video is neither in Youtube history (the extension throws an error when I manually delete it) nor Chrome history. The thumbnail shows the text WATCHED but without the date (option checked in my options) and there is no progressbar (I don't hide the progressbar in the options) If I click on the link, the name of the video and the date on the thumbnail appear.

> I just made some modifications, does the attached version improve things? Make sure to backup your database before you try.

So far, it seems to be fixed with this version for me, thank you. Let's see in a few days :)

By the way: 
![image](https://github.com/sniklaus/youtube-watchmarker/assets/52289398/2b8a4a33-8f3d-4181-a1e6-57a8d5d5d9ea)

**Comment by peachlilac** [comment]
> I just made some modifications, does the attached version improve things? Make sure to backup your database before you try.
> 
> * [chrome.zip](https://github.com/sniklaus/youtube-watchmarker/files/13945734/chrome.zip)
> * [firefox (rename the extension to xpi).zip](https://github.com/sniklaus/youtube-watchmarker/files/13945735/firefox.rename.the.extension.to.xpi.zip)

I've had this version for about a week now and the main issue is fixed! The only thing I've noticed is when I started watching new videos, some of the video titles in the database are different. 

Example title in database: 'Mix - [Creator Name]'

The actual video title is completely different. I wasn't able to take a screenshot of this, but I was able to solve it by resetting the database and synchronizing my account history. So far it hasn't happened again, and I don't know what I did for that to happen.

Not sure if I should still keep this open, so I'll leave it up to the creator @sniklaus. Thanks for solving the main issue!

**Comment by sniklaus** [comment]
Thanks everyone for chiming in! I released the version you guys tested, make sure to switch to a regular install to not miss out on future updates.

> I have lines like this in my history, but with videos I didn't watched. I was able to reproduce it: whenever I visit a channel page, if there is a video above the section "Our Members", this video is added to the history of the extension with the name Videos.

Thank you for sharing this finding. Do you happen to have a link to a Youtube channel that has such an "Our Members" section? I looked at the ones I subscribe to and none do. :thinking: 

> So far, it seems to be fixed with this version for me, thank you. Let's see in a few days :)

Good news, thanks for letting me know!

> I've had this version for about a week now and the main issue is fixed! The only thing I've noticed is when I started watching new videos, some of the video titles in the database are different.

Please don't hesitate to reach out again should this issue come back. Could very well be a bug.

**Comment by L0relei** [comment]
> Thank you for sharing this finding. Do you happen to have a link to a Youtube channel that has such an "Our Members" section? I looked at the ones I subscribe to and none do. 🤔

For instance: https://www.youtube.com/@KatherineOfSky
![image](https://github.com/sniklaus/youtube-watchmarker/assets/52289398/3050ead6-9f46-4486-819c-4129e3fa05c8)

By the way, this is an example of a video that has been marked as watched by the extension but that I didn't watch and that isn't in my history (Youtube and Chrome) It was marked as watched before installing the new version.



> > So far, it seems to be fixed with this version for me, thank you. Let's see in a few days :)
> 
> Good news, thanks for letting me know!

I confirm that I no longer have the issue with the new version, thank you again!

**Comment by sniklaus** [comment]
Closing this issue for now since it seems resolved? Please reopen if I am/was mistaken.

**Comment by Dryparn** [comment]
I'm sadly still having this problem on 4.6.1

Plugins:
Alternate Player for Twitch.tv
Enhancer for Youtube
uBlock Origin
Window Titler
Youtube Watchmaker
